MODEL:
  pc_model: 'pn2_patchlets' # which model to use for point cloud processing, pn1 | pn2 | pn1_4d_basic | pn2_4d_basic | pn2_patchlets | 3dmfv (check)
  3DMFV:
    n_gaussians: 8
  PATCHLET:
    centroid_jitter: 0.005
    sample_mode: 'nn'  # nn | randn | gt type of patchlet sampling
    k: 16
    downsample_method: 'fps'
    radius: [null, null, null]

TRAINING:
  lr: 0.001
  steps_per_update: 2
  batch_size: 8
  n_epochs: 200
  refine: False
  refine_epoch: 0
  pretrained_model: null
  aug: [''] # '' | 'scale', 'translate'

TESTING:
  batch_size: 2
  aug: [''] # '' | 'scale', 'translate'
  set: 'test'

DATA:
  dataset_path: '/data/sitzikbs/datasets/dfaust/'
#  dataset_path: '/home/shrout/Hera/data1/datasets/dfaust/' # TODO: for debug (remove)
  frames_per_clip: 64 #32
  frame_skip: 1
  n_points: 1024
  shuffle_points: 'fps_each_frame' # 'each | none | fps_each_frame| fps_each '
  gender: 'all'
  data_sampler: 'weighted'
  noisy_data:
    train: False #False
    test: False #False
