seed: 0
save_every: 5
num_workers: 0

MODEL:
  pc_model: 'set_transformer' # which model to use for point cloud processing tpatches, set_transformer, tpatch_trajectory, pn2_patchlets,
  3DMFV:
    n_gaussians: 8
  SET_TRANSFORMER:
    dim_input: 3
    num_outputs: 1
    num_inds: 32
    dim_hidden: 512
    num_heads: 4
    ln: False
    temporal_smoothing: 0
  TPATCHES:
    centroid_jitter: 0.001
    sample_mode: 'randn'  # nn | randn | gt type of patchlet sampling
    k: [ 16, 16, 16 ]
    npoints: [ 512, 128, null ]
    temp_conv: 7
    downsample_method: 'var' # fps (not working), var, mean_var_t, 
    radius: [null, null, null]
    type: 'skip_con' # 'origin' / 'skip_con' / 'attn_last_layer' / 'attn_all_layers'
    attn_num_heads: 4 # only applicable with 'attn_last_layer' or 'attn_all_layers'
    bidirectional: True # True | False to use bidirectional t-patches

TRAINING:
  lr: 0.001
  steps_per_update: 8
  batch_size: 2
  n_epochs: 24 # 61
  refine: False
  refine_epoch: 0
  pretrained_model: null
  aug: [''] # '' | 'scale', 'translate'

TESTING:
  batch_size: 2
  aug: ['']
  set: 'test'

DATA:
  name: 'IKEA_ASM'
  dataset_path: 'datasets\data\IKEA ASM\ANU_ikea_dataset_smaller_clips\32'
  frame_skip: 1
  frames_per_clip: 32
  data_sampler: 'weighted'
  n_points: 4096
  in_channel: 6 # 3 | 6 -> xyz, xyzrgb
